services:
  db:
    image: timescale/timescaledb:2.14.2-pg13
    ports:
      - 5432:5432
    environment:
     - POSTGRES_USER=erp
     - POSTGRES_PASSWORD=erp
    command: >
      postgres
        -c max_worker_processes=20
        -c max_parallel_workers=8
        -c max_parallel_workers_per_gather=4
        -c timescaledb.max_background_workers=8
    volumes:
      - ./db:/var/lib/postgresql/data

  mongo:
    image: mongo:3.0
    ports:
      - 27017:27017

  redis:
    image: redis:5.0
    ports:
      - 6379:6379
