from emission_tests import *
from investment_tests import *
from assignment_tests import *
from partner_tests import *
from somenergia_soci_tests import *
from test_wizard_baixa_soci import *
from fareperiodcurve_tests import *
from wizard_llibre_tests import *
from investment_strategy_tests import *
from wizard_generate_mandate_tests import *
