# -*- coding: utf-8 -*-
import wizard_investment_activation
import wizard_investment_amortization
import wizard_investment_payment
import wizard_investment_creation
import wizard_investment_cancel_or_resign
import wizard_investment_divest
import wizard_investment_transfer
import wizard_aeat193_from_gkwh_invoices
import wizard_baixa_soci
import wizard_contract_sign_signaturit
import wizard_llibre_registre_socis
import wizard_factures_liquidacio_interessos
import wizard_generate_mandate
