# -*- coding: utf-8 -*-
{
    "name": "SomEnergia Productive Base Profile",
    "description": """
    Mòdul perfil per construir una base de dades buida
    amb el mateix stack funcional que productiu.
    """,
    "version": "0-dev",
    "author": "Som Energia",
    "category": "SomEnergia",
    "depends": [
        "account_analytic_distribution",
        "account_chart_coop_es",
        "account_import_facturae",
        "account_renumber",
        "db_utils",
        "devolucions_base_som",
        "dx_invoice_supplier_renumber",
        "giscedata_administracio_publica_miteco",
        "giscedata_atc_facturacio_switching",
        "giscedata_atc_switching_comer",
        "giscedata_cne_circular_2_2005",
        "giscedata_cnmc_infde006614_comer",
        "giscedata_cnmc_ivc",
        "giscedata_cnmc_requeriments",
        "giscedata_crm_leads_facturacio_indexada",
        "giscedata_crm_leads_sips",
        "giscedata_dfestius",
        "giscedata_escila",
        "giscedata_facturacio_bateria_virtual_polissa_category",
        "giscedata_facturacio_devolucions",
        "giscedata_facturacio_fraccionaments",
        "giscedata_facturacio_full_consums_repercussio_ajust_gas",
        "giscedata_facturacio_pool",
        "giscedata_facturacio_reactiva_llistats",
        "giscedata_facturacio_refund_signed",
        "giscedata_informes_comptables_llum",
        "giscedata_measures_comer",
        "giscedata_polissa_name_auto",
        "giscedata_reganecu",
        "giscedata_serveis_generacio_switching",
        "giscedata_sips",
        "giscedata_switching_cnmc_reports",
        "giscedata_switching_estimacio",
        "giscedata_tarifas_cargos_20210601",
        "giscedata_tarifas_cargos_20210916",
        "giscedata_tarifas_cargos_20220101",
        "giscedata_tarifas_cargos_20220301",
        "giscedata_tarifas_cargos_20230101",
        "giscedata_tarifas_pagos_capacidad_20180101",
        "giscedata_tarifas_pagos_capacidad_20190101",
        "giscedata_tarifas_pagos_capacidad_20210601",
        "giscedata_tarifas_pagos_capacidad_20220101",
        "giscedata_tarifas_pagos_capacidad_20230101",
        "giscedata_tarifas_peajes_20100701",
        "giscedata_tarifas_peajes_20110401",
        "giscedata_tarifas_peajes_20111001",
        "giscedata_tarifas_peajes_20111223",
        "giscedata_tarifas_peajes_20120101",
        "giscedata_tarifas_peajes_20120401",
        "giscedata_tarifas_peajes_20130801",
        "giscedata_tarifas_peajes_20140201",
        "giscedata_tarifas_peajes_20150101",
        "giscedata_tarifas_peajes_20160101",
        "giscedata_tarifas_peajes_20170101",
        "giscedata_tarifas_peajes_20180101",
        "giscedata_tarifas_peajes_20190101",
        "giscedata_tarifas_peajes_20200101",
        "giscedata_tarifas_peajes_20210601",
        "giscedata_tarifas_peajes_20210916",
        "giscedata_tarifas_peajes_20220101",
        "giscedata_tarifas_peajes_20220301",
        "giscedata_tarifas_peajes_20230101",
        "giscedata_tarifas_peajes_20240101",
        "giscedata_telegestio_comer_switching",
        "giscedata_tipovia_catastro",
        "giscemisc_informes_scheduler",
        "giscere_facturacio_casacio",
        "giscere_facturacio_facturae",
        "giscere_facturacio_refund_signed",
        "giscere_medidas",
        "giscere_tarifas_representacio_2021",
        "giscere_tarifas_representacio_2022",
        "giscere_tarifas_representacio_2023",
        "giscere_tarifas_representacio_2024",
        "giscere_tarifas_representacio_2025",
        "giscere_tarifas_representacio_2026",
        "ir_access_wizard",
        "ir_attachment_mongodb",
        "l10n_ES_account_balance_report",
        "l10n_ES_aeat_mod193_from_invoice",
        "l10n_ES_aeat_mod347_sql",
        "l10n_ES_cierre_ejercicio",
        "partner_address_tipovia_trg",
        "partner_blacklist",
        "poweremail_oorq",
        "report_tester",
        "res_comarca_canaries",
        "res_comarca_ib",
        "som_autofactura",
        "som_control_reports",
        "som_custom_views",
        "som_dashboard",
        "som_documents_sensibles",
        "som_empowering",
        "som_energetica",
        "som_estalvi",
        "som_extend_facturacio_facturae",
        "som_facturacio_calculada",
        "som_facturacio_flux_solar",
        "som_factures_paper",
        "som_gurb",
        "som_informe",
        "som_l10n_ES_aeat_mod347",
        "som_municipal_taxes",
        "som_remeses_base",
        "som_sortida",
        "som_stash",
        "som_sync_openerp",
        "som_telemesura",
        "som_webforms_helpers",
        "somre_giscere_facturacio",
        "somre_giscere_oferta",
        "somre_ov_module",
        "uiqmako_helpers",
        "ws_transactions",
    ],
    "init_xml": [],
    "demo_xml": [],
    "update_xml": [],
    "active": False,
    "installable": True,
}
