import giscedata_bateria_virtual_percentatges_acumulacio
import giscedata_bateria_virtual_origen
import giscedata_bateria_virtual
import giscedata_bateria_virtual_polissa
from giscedata_polissa import *
