# -*- coding: utf-8 -*-
from __future__ import absolute_import
import wizard_revert_incident_fact_contracte_lot
import wizard_open_factures_send_mail
import wizard_move_contracts_to_prev_lot
import wizard_informe_factures_dades_desagregades
import wizard_afegir_contracte_bateria_virtual
