from .update_pending_states_tests import *
from .test_som_consulta_pobresa import *
from .test_wizard_create_som_consulta_pobresa import *
from .test_giscedata_polissa import *
from .wizard_returned_invoices_export_tests import *
from .wizard_unlink_sms_pending_history_tests import *
from .wizard_tugesto_invoices_export_tests import *
from .wizard_pay_invoice_tests import *
from .account_invoice_tests import *
