server {
    listen 8081;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location /api {
        proxy_pass http://localhost:8068/;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_read_timeout 86400;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
