[options]
without_demo = True
netrpc = False
xmlrpc = True
interface = 0.0.0.0
port = 8069
price_accuracy = 6
stop_after_init = False
log_level = info

root_path = /opt/somenergia/src/erp/server/bin
addons_path = /opt/somenergia/src/erp/server/bin/addons

db_host = postgres
db_port = 5432
db_user = erp
db_password = erp

environment = ci
redis_url = redis://redis:6379/0
mongodb_uri = mongodb://mongo:27017/erp_runtime
