# This workflow is disabled because Github is not supporting matrix output separatly by job: PR https://github.com/actions/runner/pull/2477

name: SOM_MODULES_PY3
on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 1 * *'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  POSTGRES_USER: erp
  POSTGRES_PASSWORD: erp

jobs:
  list-modules:
    name: List of modules
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: |
          echo "matrix=$(ls -d */ | sed 's|[/]||g' | egrep -v '^scripts|docs' | jq -R -s -c 'split("\n")[:-1]')" >> "$GITHUB_OUTPUT"

  test-modules:
    name: test-modules
    needs: [list-modules]
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        module: ${{ fromJson(needs.list-modules.outputs.matrix) }}
    uses: ./.github/workflows/reusable_workflow.yml
    with:
      module: ${{matrix.module}}
      erpbranch: rolling_erp01
      all_modules: true
      pyversion: '[ "3.10" ]'
    secrets: inherit
