name: Workflow secrets not working from steps
on:
  workflow_dispatch:

jobs:
  call-workflow-from-job-with-secrets:
    uses: octo-org/example-repo/.github/workflows/reusable-workflow.yml@main
    with:
      config-path: .github/labeler.yml
    secrets:
      envPAT: ${{ secrets.SRID }}
  call-workflow-from-job-with-secrets-from-steps:
    name: Run PR tests
    runs-on: ubuntu-latest
    steps:
      - uses: octo-org/example-repo/.github/workflows/reusable-workflow.yml@main
        with:
          config-path: .github/labeler.yml
        secrets:
          envPAT: ${{ secrets.SRID }}
