# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: SOM_ERP
on:
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  POSTGRES_USER: erp
  POSTGRES_PASSWORD: erp

jobs:
  build:
    name: Test PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Get changed modules in PR
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          dir_names: 'True'
          dir_names_exclude_current_dir: 'True'
          dir_names_max_depth: '1'

      - name: Run tests
        uses: ./.github/workflows/reusable_workflow.yml
        with:
          module: ''
