name: Keep PRs alive

on:
  schedule:
    # Cada 90 dies
    - cron: "0 3 */90 * *"
  workflow_dispatch:

jobs:
  ping-stale-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Ping and un-stale PRs
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN_GA }}
        run: |
          REPO="gisce/erp"
          TOKEN="$GITHUB_TOKEN"
          API="https://api.github.com/repos/$REPO"

          page=1
          found=0

          page=1
          while :; do
            echo "Desubscrivint pàgina $page de notifactions..."
            notifications=$(curl -s -H "Authorization: token $TOKEN" \
              "$API/notifications")

            count=$(echo "$notifications" | jq '. | length')
            if [ "$count" -eq 0 ]; then
              echo "No queden més notifications."
              break
            fi
            threads_id=$(echo "$notifications" | jq -r '
              .[] | select(.repository.full_name == "'$REPO'" and .subject.type == "PullRequest") | .id
            ')
            for thread_id in $threads_id; do
              echo "Desubscrivint thread $thread_id"
              curl -s -X DELETE -H "Authorization: token $TOKEN" \
                "$API/notifications/threads/$thread_id/subscription" > /dev/null
            done
            page=$((page+1))
          done
          echo "Processades $found PRs amb label Stale d'aquests usuaris."
