name: Keep PRs alive

on:
  schedule:
    # Cada 85 dies aprox. (segurament vols una mica menys, per exemple cada 60 dies)
    - cron: "0 3 */60 * *"
  workflow_dispatch:

jobs:
  ping-stale-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Ping and un-stale PRs
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN_GA }}
        run: |
          REPO="gisce/erp"
          TOKEN="$GITHUB_TOKEN"
          API="https://api.github.com/repos/$REPO"

          # Buscar pulls (PRs) obertes amb label 'Stale'
          pulls=$(curl -s -H "Authorization: token $TOKEN" \
            "$API/pulls?state=open&labels=Stale")

          # Filtrar només PRs de dos usuaris
          prs=$(echo "$pulls" | jq -r '.[] | select(.user.login=="oriolpiera" or .user.login=="FranciscoCubero") | .number')

          if [ -z "$prs" ]; then
            echo "Cap PR stale trobada d'aquests usuaris."
            exit 0
          fi

          for pr in $prs; do
            echo "Comentant i traient 'Stale' de la PR #$pr"

            # Afegir comentari
            curl -s -X POST -H "Authorization: token $TOKEN" \
              -d '{"body":"👋 Encara vigent"}' \
              "$API/pulls/$pr/comments" > /dev/null

            # Treure etiqueta 'Stale'
            curl -s -X DELETE -H "Authorization: token $TOKEN" \
              "$API/pulls/$pr/labels/Stale" > /dev/null
          done
