# This workflow will pass tests of module passed by input

name: som_account_invoice_pending
on:
  schedule:
    - cron: '0 0 * * 1'
  pull_request:
    branches: [ main ]
jobs:
  erp-tests-module:
    uses: ./.github/workflows/reusable_workflow.yml
    with:
      module: som_account_invoice_pending
    secrets:
      ACCESS_TOKEN_GA: ${{ secrets.ACCESS_TOKEN_GA }}
      ESIOS_TOKEN: ${{ secrets.ESIOS_TOKEN }}
      SRID: ${{ secrets.SRID }}