name: Send README by email
on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4.1.1

      - name: Converts Markdown to HTML
        uses: jaywcjlove/markdown-to-html-cli@main
        with:
          source: README.md
          output: README.html
          github-corners: https://github.com/jaywcjlove/markdown-to-html-cli
          favicon: data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🌐</text></svg>

      - name: send mail
        uses: dawidd6/action-send-mail@v3.11.0
        with:
          connection_url: ${{secrets.MAIL_CONNECTION}}
          subject: Resultats tests repo OpenERP Som Addons
          to: ${{secrets.MAIL_DESTINATION}}
          from: El sentinela del ERP <elsentinela@somenergia.coop>
          html_body: file://README.html
          server_port: 587
          secure: true
